FROM dockerswarm/swarm:master

ADD cluster /srv/cluster
CMD ["manage", "--strategy=spread", "--tlsverify", "--tlscacert={{ docker_tls_path }}/ca.pem", "--tlscert={{ docker_tls_path }}/cert.pem", "--tlskey={{ docker_tls_path }}/key.pem", "-H=127.0.0.1:2376", "file:///srv/cluster"]
