#!/usr/bin/env python

import yaml
from collections import OrderedDict

# from http://stackoverflow.com/questions/8640959/how-can-i-control-what-scalar-form-pyyaml-uses-for-my-data
class literal(str): pass

def literal_presenter(dumper, data):
    return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
yaml.add_representer(literal, literal_presenter)

def ordered_dict_presenter(dumper, data):
    return dumper.represent_dict(data.items())
yaml.add_representer(OrderedDict, ordered_dict_presenter)


with open("secrets.yml", "r") as fh:
    orig_secrets = yaml.load(fh.read())
del orig_secrets["ca_cert"]
del orig_secrets["tls_certs"]
del orig_secrets["tls_keys"]

secrets = OrderedDict()
for secret in sorted(orig_secrets.keys()):
    val = orig_secrets[secret]
    if isinstance(val, str) and len(val.split("\n")) == 1:
        secrets[secret] = val
for secret in sorted(orig_secrets.keys()):
    val = orig_secrets[secret]
    if not isinstance(val, str):
        secrets[secret] = val
for secret in sorted(orig_secrets.keys()):
    val = orig_secrets[secret]
    if isinstance(val, str) and len(val.split("\n")) > 1:
        secrets[secret] = literal(val)

with open("certificates/ca.pem", "r") as fh:
    secrets["ca_cert"] = literal(fh.read())

secrets["tls_certs"] = OrderedDict()
secrets["tls_keys"] = OrderedDict()

with open("certificates/compmodels-cert.pem", "r") as fh:
    secrets["tls_certs"]["jupyterhub_host"] = literal(fh.read())
with open("certificates/compmodels-key.pem", "r") as fh:
    secrets["tls_keys"]["jupyterhub_host"] = literal(fh.read())

for i in range(1, 8):
    with open("certificates/compmodels-node-0%d-cert.pem" % i, "r") as fh:
        secrets["tls_certs"]["jupyterhub_node%d" % i] = literal(fh.read())
    with open("certificates/compmodels-node-0%d-key.pem" % i, "r") as fh:
        secrets["tls_keys"]["jupyterhub_node%d" % i] = literal(fh.read())

with open("secrets.yml", "w") as fh:
    fh.write("---\n")
    fh.write(yaml.dump(secrets, default_flow_style=False))
