#!/bin/bash

ROOT=$(dirname $0)/..

if [ ! -e ${ROOT}//inventory ]; then
  echo "Please create an inventory file with your hosts."
  echo " cp inventory.example inventory"
  exit 1
fi

VAULT_ARG=--vault-password-file ${ROOT}/vault-password
exec ansible-playbook ${ROOT}/deploy.yml -i ${ROOT}/inventory ${VAULT_ARG} $@
