FROM dockerswarm/swarm:master

ADD cluster /srv/cluster
CMD ["manage", "--strategy={{ docker_swarm_strategy }}", "--tlsverify", "--tlscacert={{ docker_tls_path }}/ca.pem", "--tlscert={{ docker_tls_path }}/cert.pem", "--tlskey={{ docker_tls_path }}/key.pem", "-H=127.0.0.1:{{ docker_swarm_port }}", "file:///srv/cluster"]
